---
title: "Usefull stuff"
format: html
editor: visual
bibliography: references.bib
---

# Books

1.  [Carl Edward Rasmussen and Christopher K. I. Williams. The MIT Press, 2006. ISBN 0-262-18253-X](https://gaussianprocess.org/gpml/)
2.  @ghosh2021a
3.  @hemachandran2022
4.  @james2021
5.  @lifshits2012
6.  @zili2018a

# Articles

1.  Wang, J. (2022). *An intuitive tutorial to gaussian processes regression* (arXiv:2009.10862). arXiv. <http://arxiv.org/abs/2009.10862>
2.  Schulz, E., Speekenbrink, M., & Krause, A. (2018). A tutorial on gaussian process regression: Modelling, exploring, and exploiting functions. *Journal of Mathematical Psychology*, *85*, 1--16. <https://doi.org/10.1016/j.jmp.2018.03.001>
3.  

# Web documents

1.  [Probabilistic Machine Learning](https://research.cs.aalto.fi//pml/software/gpstuff/)
2.  [Yes but what is a Gaussian process?](https://dansblog.netlify.app/posts/2021-11-03-yes-but-what-is-a-gaussian-process-or-once-twice-three-times-a-definition-or-a-descent-into-madness/yes-but-what-is-a-gaussian-process-or-once-twice-three-times-a-definition-or-a-descent-into-madness.html)
3.  [Priors for the parameters in a Gaussian process](https://dansblog.netlify.app/posts/2022-09-07-priors5/priors5.html)
4.  [Medium. Gaussian Process Models](https://towardsdatascience.com/gaussian-process-models-7ebce1feb83d)
5.  [Gaussian processes (1/3) - From scratch](https://peterroelants.github.io/posts/gaussian-process-tutorial/)
6.  [Gaussian processes (2/3) - Fitting a Gaussian process kernel](https://peterroelants.github.io/posts/gaussian-process-kernel-fitting/)
7.  [Gaussian processes (3/3) - exploring kernels](https://peterroelants.github.io/posts/gaussian-process-kernels/)
8.  [Multivariate Normal Distribution](https://peterroelants.github.io/posts/multivariate-normal-primer/)
9.  [visual-exploration-gaussian-processes](https://distill.pub/2019/visual-exploration-gaussian-processes/)
10. https://rpubs.com/ncahill_stat/889056 (this is in R)
11. https://www.cs.toronto.edu/\~duvenaud/cookbook/
12. http://www.tmpl.fi/gp/

# Videos

1.  [Introduction to Gaussian processes](https://www.youtube.com/watch?v=GWHE5vnpxks&list=PLZ_xn3EIbxZHynuWRdYp4WDtpKm5Xo9Ge)
2.  [Gaussian processes for fun and profit: Probabilistic machine learning in industry](https://www.youtube.com/watch?v=uq8VxqeHPj8)
3.  [Support Vector Machine The Kernel Trick RBF Function](https://www.youtube.com/watch?v=e4qWknGNzB0)
4.  https://www.youtube.com/watch?v=5Cqi-RAwAu8

# Apps

1.  [Interactive Gaussian Process Visualization](http://www.infinitecuriosity.org/vizgp/)
2.  [shiny](https://durrande.shinyapps.io/gp_playground/)
3.  [Interactive visualizations](https://github.com/st--/interactive-gp-visualization)

# Software

1.  https://github.com/SheffieldML/GPy
2.  

# Podcast

1.  http://www.thetalkingmachines.com/
